.TH DXCC 1 "VERSION" Linux "User Manuals"
.SH NAME
dxcc \- ham radio callsign DXCC lookup utility
.SH SYNOPSIS
.B dxcc [-g] [-m MYPREFIX] [CALLSIGN]
.SH DESCRIPTION
.B dxcc
determines the ARRL DXCC entity of a ham radio callsign, based on the
cty.dat country file by Jim Reisert, AD1C (http://country-files.com/).

If a matching country or entity is found, the entity name, continent,
latitude/longitude and other information are printed.

When invoked with the command line option 
.B -g
, a Perl/Tk GUI with an additional world map showing the location of the
DXCC is shown.

If the line option 
.B -m [MYPREFIX]
is used, the distance and bearing to CALLSIGN is calculated and displayed.

.SH FILES
.I /usr/(local/)share/dxcc/cty.dat
.RS
.I Optional
country file. A current version of AD1C's country file is already included in
dxcc.
.RE
.I /usr/(local/)share/dxcc/earth.gif
.RS
Earth picture for the GUI.
.RE

.SH AUTHOR
Fabian Kurz, DJ1YFK <fabian@fkurz.net> - https://fkurz.net/ham/dxcc.html
